# Generated by Django 6.0.7 on 2026-07-13 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libro', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_prestamo', models.DateField()),
                ('fecha_devolucion', models.DateField()),
                ('devuelto', models.BooleanField(default=False)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='libro.libro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuario.usuario')),
            ],
        ),
    ]
